# Generated by Django 3.1.3 on 2020-12-11 13:19

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0002_auto_20201211_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=10)),
                ('experience', models.CharField(max_length=200)),
                ('questions', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=400, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.user')),
            ],
        ),
    ]
